/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BLACKJACK_H_RPCGEN
#define _BLACKJACK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct comms {
	char card_1[4];
	char card_2[4];
	char dealer_card[4];
	char msg[50];
	char player_call[10];
};
typedef struct comms comms;

#define BLACKJACK 2
#define VERSION 2

#if defined(__STDC__) || defined(__cplusplus)
#define process_call 1
extern  comms * process_call_2(comms *, CLIENT *);
extern  comms * process_call_2_svc(comms *, struct svc_req *);
extern int blackjack_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define process_call 1
extern  comms * process_call_2();
extern  comms * process_call_2_svc();
extern int blackjack_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_comms (XDR *, comms*);

#else /* K&R C */
extern bool_t xdr_comms ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BLACKJACK_H_RPCGEN */
